# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b209fcd99da488f4d3e801852deae1fcc5e3da9d910e843b22e1725e8c7bfa81b456e8c155eec2d64a886c534ec708eb96e606f65489e9e2c32af6bf0b806c1c

test:
  secret_key_base: c933907fa9b0eeda80d67582725d6db5fb1c820574b8e152cb8703d74b560b3eed91aee8bd9ee8158767477cf054ddd6a54de61b392801c51798ed79dec1ae5f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
